name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:  

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: CaioHenryxz
          svg_out_path: github-contribution-grid-snake.svg  
      - name: List files to confirm the snake file exists
        run: ls -la  
      - name: Upload Snake GIF as artifact
        uses: actions/upload-artifact@v2  
        with:
          name: snake-gif
          path: github-contribution-grid-snake.svg  
